import { StyleSheet, Font } from "@react-pdf/renderer";

Font.register({
  family: "Roboto",
  fonts: [
    {
      src: "https://cdnjs.cloudflare.com/ajax/libs/ink/3.1.10/fonts/Roboto/roboto-light-webfont.ttf",
      fontWeight: "normal",
    },
    {
      src: "https://cdnjs.cloudflare.com/ajax/libs/ink/3.1.10/fonts/Roboto/roboto-bold-webfont.ttf",
      fontWeight: "bold",
    },
    {
      src: "https://cdnjs.cloudflare.com/ajax/libs/ink/3.1.10/fonts/Roboto/roboto-italic-webfont.ttf",
      fontStyle: "italic",
    },
  ],
});

export const styles = {
  style1: StyleSheet.create({
    page: {
      backgroundColor: "#E4E4E4",
      fontFamily: "Roboto",
      paddingBottom: 80,
    },
    cvTitle: {
      fontFamily: "Roboto",
      fontSize: 35,
      fontWeight: "bold",
    },
    section: {
      margin: 10,
      padding: 10,
    },
    image: {
      width: "99px",
      height: "129px",
      objectFit: "cover",
      marginRight: 50,
    },
    imageIcon: {
      marginLeft: 100,
    },
    personalData: {
      fontFamily: "Roboto",
      fontSize: 14,
      fontWeight: "normal",
    },
    personalInfo: {
      fontSize: 16,
      fontFamily: "Roboto",
      color: "black",
      fontWeight: "bold",
    },
    info: {
      fontSize: 16,
      fontFamily: "Roboto",
      color: "black",
      fontWeight: "bold",
      marginLeft: 30,
      marginBottom: 15,
      marginTop: 15,
    },
    personalDataSection: {
      border: "1px solid black",
      padding: 10,
      flexDirection: "row",
    },
    otherDataSection: {
      marginTop: 10,
      fontFamily: "Roboto",
      fontWeight: "normal",
      fontSize: 14,
    },
    clause: {
      position: "absolute",
      left: 30,
      right: 30,
      bottom: 30,
      fontSize: 12,
      fontFamily: "Roboto",
      fontWeight: "normal",
      color: "grey",
      fontStyle: "italic",
    },
    skillSection: {
      justifyContent: "center",
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
      marginRight: 50,
      marginLeft: 50,
    },
    skillText: {
      margin: 5,
      textAlign: "center",
    },
    hobbySection: {
      justifyContent: "center",
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
      marginRight: 50,
      marginLeft: 50,
    },
    hobbyText: {
      margin: 5,
      textAlign: "center",
    },
  }),
  style2: StyleSheet.create({
    page: {
      backgroundColor: "#337EF5",
      fontFamily: "Roboto",
      paddingBottom: 80,
    },
    cvTitle: {
      fontFamily: "Roboto",
      fontSize: 35,
      fontWeight: "bold",
    },
    section: {
      margin: 10,
      padding: 10,
    },
    image: {
      width: "99px",
      height: "129px",
      objectFit: "cover",
      marginRight: 50,
    },
    imageIcon: {
      marginLeft: 100,
    },
    personalData: {
      fontFamily: "Roboto",
      fontSize: 14,
      fontWeight: "normal",
    },
    personalInfo: {
      fontSize: 16,
      fontFamily: "Roboto",
      color: "black",
      fontWeight: "bold",
    },
    info: {
      fontSize: 16,
      fontFamily: "Roboto",
      color: "black",
      fontWeight: "bold",
      marginLeft: 30,
      marginBottom: 15,
      marginTop: 15,
    },
    personalDataSection: {
      border: "1px solid black",
      padding: 10,
      flexDirection: "row",
    },
    otherDataSection: {
      marginTop: 10,
      fontFamily: "Roboto",
      fontWeight: "normal",
      fontSize: 14,
    },
    clause: {
      position: "absolute",
      left: 30,
      right: 30,
      bottom: 30,
      fontSize: 12,
      fontFamily: "Roboto",
      fontWeight: "normal",
      color: "grey",
      fontStyle: "italic",
    },
    skillSection: {
      justifyContent: "center",
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
      marginRight: 50,
      marginLeft: 50,
    },
    skillText: {
      margin: 5,
      textAlign: "center",
    },
    hobbySection: {
      justifyContent: "center",
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
      marginRight: 50,
      marginLeft: 50,
    },
    hobbyText: {
      margin: 5,
      textAlign: "center",
    },
  }),
  style3: StyleSheet.create({
    page: {
      backgroundColor: "#E7F283",
      fontFamily: "Roboto",
      paddingBottom: 80,
    },
    cvTitle: {
      fontFamily: "Roboto",
      fontSize: 35,
      fontWeight: "bold",
    },
    section: {
      margin: 10,
      padding: 10,
    },
    image: {
      width: "99px",
      height: "129px",
      objectFit: "cover",
      marginRight: 50,
    },
    imageIcon: {
      marginLeft: 100,
    },
    personalData: {
      fontFamily: "Roboto",
      fontSize: 14,
      fontWeight: "normal",
    },
    personalInfo: {
      fontSize: 16,
      fontFamily: "Roboto",
      color: "black",
      fontWeight: "bold",
    },
    info: {
      fontSize: 16,
      fontFamily: "Roboto",
      color: "black",
      fontWeight: "bold",
      marginLeft: 30,
      marginBottom: 15,
      marginTop: 15,
    },
    personalDataSection: {
      border: "1px solid black",
      padding: 10,
      flexDirection: "row",
    },
    otherDataSection: {
      marginTop: 10,
      fontFamily: "Roboto",
      fontWeight: "normal",
      fontSize: 14,
    },
    clause: {
      position: "absolute",
      left: 30,
      right: 30,
      bottom: 30,
      fontSize: 12,
      fontFamily: "Roboto",
      fontWeight: "normal",
      color: "grey",
      fontStyle: "italic",
    },
    skillSection: {
      justifyContent: "center",
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
      marginRight: 50,
      marginLeft: 50,
    },
    skillText: {
      margin: 5,
      textAlign: "center",
    },
    hobbySection: {
      justifyContent: "center",
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
      marginRight: 50,
      marginLeft: 50,
    },
    hobbyText: {
      margin: 5,
      textAlign: "center",
    },
  }),
  style4: StyleSheet.create({
    page: {
      backgroundColor: "#F246EA",
      fontFamily: "Roboto",
      paddingBottom: 80,
    },
    cvTitle: {
      fontFamily: "Roboto",
      fontSize: 35,
      fontWeight: "bold",
    },
    section: {
      margin: 10,
      padding: 10,
    },
    image: {
      width: "99px",
      height: "129px",
      objectFit: "cover",
      marginRight: 50,
    },
    imageIcon: {
      marginLeft: 100,
    },
    personalData: {
      fontFamily: "Roboto",
      fontSize: 14,
      fontWeight: "normal",
    },
    personalInfo: {
      fontSize: 16,
      fontFamily: "Roboto",
      color: "black",
      fontWeight: "bold",
    },
    info: {
      fontSize: 16,
      fontFamily: "Roboto",
      color: "black",
      fontWeight: "bold",
      marginLeft: 30,
      marginBottom: 15,
      marginTop: 15,
    },
    personalDataSection: {
      border: "1px solid black",
      padding: 10,
      flexDirection: "row",
    },
    otherDataSection: {
      marginTop: 10,
      fontFamily: "Roboto",
      fontWeight: "normal",
      fontSize: 14,
    },
    clause: {
      position: "absolute",
      left: 30,
      right: 30,
      bottom: 30,
      fontSize: 12,
      fontFamily: "Roboto",
      fontWeight: "normal",
      color: "grey",
      fontStyle: "italic",
    },
    skillSection: {
      justifyContent: "center",
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
      marginRight: 50,
      marginLeft: 50,
    },
    skillText: {
      margin: 5,
      textAlign: "center",
    },
    hobbySection: {
      justifyContent: "center",
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
      marginRight: 50,
      marginLeft: 50,
    },
    hobbyText: {
      margin: 5,
      textAlign: "center",
    },
  }),
};
